name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  workflow_dispatch:

# The release job creates a GitHub release, so grant write access to contents.
permissions:
  contents: write

jobs:
  release:
    uses: wppoland/workflows/.github/workflows/_release-free.yml@v1
    with:
      slug: trust
      wporg-slug: trust
      has-js: false
    secrets:
      WPORG_SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
